### ISSUE TITLE
Add a COVID-19 alert

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/course_reserves#214]

**Comment by saseestone** [comment]
text should be:

COVID-19 update
Instructors please submit your course reserves requests for Spring Quarter 2020 as soon as possible. Library staff will work to determine what e-resources are available for purchase or licensing as surrogates for print and media materials. If digital surrogates cannot be found in a timely manner, library staff will contact you with other options. If you have any questions, please contact coursereserves@stanford.edu
