### ISSUE TITLE
Minor changes to new CREZ styles

### ISSUE THREAD

**Issue by jvine** [sul-dlss/course_reserves#247]
Some minor changes for consistency:

- [x] change font weight for headings from 500 to 100
- [x] make the white `<header>` 35px high 
- [x] make the cardinal banner 100px high

<img width="1000" alt="Screen Shot 2020-07-16 at 9 31 24 AM" src="https://user-images.githubusercontent.com/6945691/87698048-ccc09500-c747-11ea-9009-55a0efc38404.png">

**Comment by mejackreed** [comment]
Re: cardinal banner height see: https://github.com/sul-dlss/earthworks/blob/master/app/assets/stylesheets/bootstrap-variables.scss#L27 for an approach
