### ISSUE TITLE
Look into CREZ slow DB load issue (CanCan #accessble_by / add sunetid index / something else?)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/course_reserves#287]

**Comment by jkeck** [comment]
Did this come through feedback somewhere?  We addressed the issue that was reported w/ #271 and seemed to confirm that it addressed the issues that were reported then.  Wasn't sure if we had received subsequent reports.

**Comment by cbeer** [comment]
👍 ; it was a card floating around on the board.

**Comment by jkeck** [comment]
Ah, sorry, that must have been my bad for not cleaning up after myself. 🧹
