### ISSUE TITLE
CREZ form updates needed for AY21-22 in July 2021

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/course_reserves#330]
Digital only reserves will end in July 2021. The form, altered for COVID-19, needs to be updated allow for instructors to input information on physical reserve requests.

**Best if we could release changes the week of July 5th**

For non full-text online titles, the form inputs under "Digital item required" should go away completely.  **Remove:**
- [x] Digital item required 
- [x] Radio buttons for "complete work" and "chapter or article"
- [x] Text box for "chapter or page range"

For all, **add:**
- [x] number of copies needed
- [x] If a personal copy is available
<strike>- [ ] If this is a request to purchase the item</strike>
- [x] Loan period drop down (options: 2 hours, 3 hours, 4 hours, 1 day, 2 days, 3 days) with default of 2 hours. Note: Users who selected Reserve desk = "MEDIA-RESV" had a restricted drop-down to 4 hours. That restriction should be re-instated.

For full-text online titles:
A hybrid solution would be best. Keep the check if the title "Full text available online", and continue to display that information to the user.  But add the input fields so that submitter can indicate if physical copies are needed (i.e. same input fields as non full-text online titles). 

Additional updates requested:
- [x] Add an input (radio button selection?) for submitter to indicate if this is a required or recommended text.  Default radio button selected should be "required"

Each change in the data inputs will need to be carried through to the staff email. 

- [x] Disable ETAS for CREZ

**Comment by saseestone** [comment]
Here's what the form inputs looked like prior to move to all-digital reserves:
![image](https://user-images.githubusercontent.com/14897546/122792888-6a351a80-d26f-11eb-8bb2-35070f08e6a2.png)

**Comment by saseestone** [comment]
Texty-text is also needed for the landing page. Working on that, and while place a draft here shortly

**Comment by cbeer** [comment]
Just confirming... you want something like this for online resources?

![Screen Shot 2021-06-23 at 07 38 53](https://user-images.githubusercontent.com/111218/123116807-11dc5500-d3f6-11eb-9983-357c047a706e.png)

**Comment by cbeer** [comment]
Slightly redesigned (with no implied colors, spacing, padding, etc...):

![Screen Shot 2021-06-23 at 15 58 56](https://user-images.githubusercontent.com/111218/123178374-eb410d00-d43b-11eb-9cb3-92bbe98d2b91.png)

**Comment by saseestone** [comment]
Homepage updates:

- [ ] Remove “Academic Year 2020-21: All course reserves will be digital”. 
- [ ] Update text block

Create or modify a list to place library materials (books, media, and licensed electronic resources) on reserve for your course. We can also circulate instructor-owned copies, and return materials to you at the end of the term.

Please save and send your list at least 7 days before materials are needed for student use. If the library must purchase materials, it may take up to 6 weeks before they are available for students.

[More information about Course Reserves](https://library.stanford.edu/using/borrow-renew-return/course-reserves)

Questions?
Contact us at coursereserves@stanford.edu or (650) 723-1492.
