### ISSUE TITLE
Users and staff can't create reserve lists

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/course_reserves#559]
Staff reported today that neither they nor Instructors can create new reserve lists at https://reserves.stanford.edu/.

I suspect this is related to the cert work that @hudajkhan has been doing, but I can't be sure. When I click on the "Create a new reserve list" the modal opens but search doesn't seem to function. No matter what is input into the search box, no results appear.

Existing lists can be edited and saved, if staff know the course list url. But search doesn't appear to work.

The last new course list was created by an Instructor last Tuesday (6/25), and the last edited course list was made on Thursday (6/27). So this is a new issue with the work deployed today.

**Comment by hudajkhan** [comment]
I believe this is related to #550 .  None of the courses will load right now in the main list because of the reserves certificate expiring.

**Comment by corylown** [comment]
@saseestone can you confirm whether this is resolved now that we've updated the certificate for harvesting course data?

**Comment by saseestone** [comment]
Yep! Resolved.  I'll close it.
